language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^8.7
    - php: 7.3
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^9.5
    - php: 7.3
      env: TYPO3_VERSION=^9.5

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini
  - composer require typo3/minimal=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/public

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" ! -path "./Vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'

before_deploy:
  - composer extension-release
  - sed -i -e "s,[0-9]\.[0-9]-dev,${TRAVIS_TAG#v},g" ext_emconf.php
  - zip -9 -r --exclude=.git/* --exclude=.Build/* web2pdf_${TRAVIS_TAG#v}.zip .

deploy:
  provider: releases
  api_key:
    secure: 1mRsmoJzBowm6/fNyKgNbLA9jk+62ERglN2mvkbk0755dR9oHuTngUB6c1Y6q/yVXViNcuT0tiRYMkeYJe4/lSeyAFGl4HrHus953X/Pj7RqzpPriWG7wxRlEsEicWggVwOklGzZgmoc+o0A08vuwSpfLgTjBeIAFfPaPjD+glMstvFp6qpjpwRCQaDHwaZYrlYICrKE4GBuZYgmxh1D6PjXp/UuCnE7uSjspBAeHik1nZISTMQaHpZEvJXGhe2wVLG9Jbtbt6Fl2BDyYdk0XedNRewAAcI63kDT2ZWeKPdFSJzJ5usJb4YcrmVUbMW3/E+xQ9h13AviQB4XJxsJSNf/V372zVUkcXBYm5CRC1J5Ig7te2EUtnJKlGuKLvFgbqerVAv1bAQfDmD1LM3HTZ/zZpCjjNDIoj7On4DI8uRDQZnt30BmL+ql9LKRNwwEJ8Eec0FqE+uqEsLLLfPCY4mpIovwGdob/HYeSDFK1l9KI1q0G2kJI7AYlh7k3nvaQAMeThc/RlhgGpkS+UfUgRNMdHcl/7cu2wa+/JIghbwcCiJuBYtt7YH/Dh5oCb6xUjIus+VBFAe1iCX0bp3oJY7K9QopY2DK9PjsRGQhFJWkKzg9WaomD1gWrMaa3ACHXN1vQKUtIRJvhxvwg+XEe9VqXzWkpMJv9uChfrhmFXA=
  file_glob: true
  file: web2pdf_*.zip
  skip_cleanup: true
  on:
    repo: mittwald/typo3-web2pdf
    tags: true
