language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - TYPO3_VERSION="7.6.0"
  - TYPO3_VERSION="^7.0"
  - TYPO3_VERSION="8.7.0"
  - TYPO3_VERSION="8.7.1"

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="8.7.0"
    - php: 5.5
      env: TYPO3_VERSION="8.7.1"
    - php: 5.6
      env: TYPO3_VERSION="8.7.0"
    - php: 5.6
      env: TYPO3_VERSION="8.7.1"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  - if [[ "$TYPO3_VERSION" == "8.7.0" || "$TYPO3_VERSION" == "8.7.1" ]]; then composer require typo3/testing-framework; fi
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    if [[ "$TYPO3_VERSION" == "8.7.0" || "$TYPO3_VERSION" == "8.7.1" ]]; then .Build/bin/phpunit -c .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit/; else .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/; fi

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'
