name: Unit tests

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
        typo3: ['^10.4']
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php == '8.0' }}
    name: PHP ${{ matrix.php }}, TYPO3 ${{ matrix.typo3 }}
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, json
        coverage: pcov
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Declare required TYPO3 version
      run: |
        composer require --no-update --dev typo3/cms-core ${{ matrix.typo3 }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      run: vendor/bin/phpunit --colors -c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
    
    - name: Run PHP lint
      run: find . -name \*.php ! -path "./.Build/*" ! -path "./Vendor/*" | xargs php -d display_errors=stderr -l {} > /dev/null \;
